run:
  skip-dirs:
    - pkg/http/v1

linters:
  enable-all: true
  disable:
    - ifshort
    - structcheck
    - deadcode
    - maligned
    - scopelint
    - golint
    - nosnakecase
    - exhaustivestruct
    - varcheck
    - interfacer
