version: '3'

vars:
  VERSION:
    sh: gitversion /showvariable SemVer

tasks:
  version:
    cmds:
      - echo {{.VERSION}}
    desc: Print current the version
    silent: true

  go:fmt:
    cmds:
      - gofumpt ./...
    desc: Formats Go programs
    silent: true

  go:lint:
    cmds:
      - golangci-lint run ./...
    desc: Check code styling rules
    preconditions:
      - test -s {{.ROOT_DIR}}/.golangci.yaml
    silent: true
