version: '3'
volumes:
  postgres:
    driver: local
networks:
  postgres:
    external: false
services:
  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - '127.0.0.1:5432:5432'

  controller-schema:
    build:
      context: ./../../
      dockerfile: ./scripts/docker/controller-schema/Dockerfile
    restart: on-failure
    command:
      - up
    environment:
      - POSTGRES_DSN=pgx://controller:controller@postgres:5432/cm?search_path=controller
    networks:
      - postgres
    volumes:
      - ./../../migrations:/migrations:ro
    depends_on:
      - postgres

  controller:
    build:
      context: ./../../
      dockerfile: ./scripts/docker/controller/Dockerfile
    restart: on-failure
    environment:
      - CONTROLLER_LOG_LEVEL=debug
      - CONTROLLER_PROFILE_ADDRESS=:8070
      - CONTROLLER_HTTP_ADDRESS=:8080
      - CONTROLLER_MONITOR_ADDRESS=:8090
      - CONTROLLER_PGX_DSN=postgres://controller:controller@postgres:5432/cm?pool_max_conns=10&pool_min_conns=5&pool_max_conn_lifetime=1h&pool_max_conn_idle_time=30m&pool_health_check_period=1m
    networks:
      - postgres
    ports:
      - '127.0.0.1:8070:8070'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8090:8090'
    depends_on:
      - controller-schema
