version: '3'
volumes:
  postgres:
    driver: local
networks:
  postgres:
    external: false
services:
  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - '127.0.0.1:5432:5432'
