openapi: 3.0.0

info:
  title: Change Management
  version: '1.0'

servers: []

components: 
  schemas: 
    $ref: schemas/_index.yml

tags:
  - name: CRQ
    description: Change request management API

  - name: IM
    description: Incident management API
      
paths: 
  /api/v1/crq:
    get:
      $ref: resources/crq/list_crq.yml
    post:
      $ref: resources/crq/create_crq.yml

  /api/v1/crq/{crqId}:
    get:
      $ref: resources/crq/get_crq.yml

  /api/v1/im:
    get:
      $ref: resources/im/list_incidents.yml
    post:
      $ref: resources/im/create_incident.yml

  /api/v1/im/{incidentId}:
    get:
      $ref: resources/im/get_incident.yml
