version: '3'

vars:
  REDOCLY_CLI_SHA: >-
    sha256:b2537e2f5858e78c1a4e1030f07a52f93aa8813e55017f95df06a338a98cf4f6

tasks:
  lint:
    cmds:
      - >-
        docker run \
          --rm \
          -v {{.ROOT_DIR}}:/spec \
          redocly/cli@{{.REDOCLY_CLI_SHA}} \
          lint api/v1/openapi.yml {{.CLI_ARGS}}
    desc: Reports on problems and executes preprocessors and rules
    preconditions:
      - test -s {{.TASKFILE_DIR}}/openapi.yml
    silent: true

  bundle:
    cmds:
      - >-
        docker run \
          --rm \
          -v {{.ROOT_DIR}}:/spec \
          redocly/cli@{{.REDOCLY_CLI_SHA}} \
          bundle /spec/api/v1/openapi.yml \
          --output /spec/api/v1/openapi.bundle.{{.EXT}} \
          --lint \
          --ext {{.EXT}}
    desc: >-
      Pulls the relevant parts of an API definition into a single file output in 
      JSON or YAML format
    sources:
      - >-
        {{.TASKFILE_DIR}}/**/*.yml
    generates:
      - >-
        {{.TASKFILE_DIR}}/openapi.bundle.{{.EXT}}
    preconditions:
      - test -s {{.TASKFILE_DIR}}/openapi.yml
    silent: true
    internal: true
  
  bundle:json:
    cmds:
      - task: bundle
        vars:
          EXT: json
    desc: >-
      Pulls the relevant parts of an API definition into a single file output in 
      JSON format
    silent: true
        
  bundle:yml:
    cmds:
      - task: bundle
        vars:
          EXT: yml
    desc: >-
      Pulls the relevant parts of an API definition into a single file output in 
      YAML format
    silent: true

  generate:
    cmds:
      - task: bundle:yml
      - test -d {{.ROOT_DIR}}/pkg/http/v1 || mkdir -p {{.ROOT_DIR}}/pkg/http/v1
      - >-
        {{.ROOT_DIR}}/bin/ogen \
          -target {{.ROOT_DIR}}/pkg/http/v1 \
          -package v1 \
          -clean \
          -generate-tests \
          -no-webhook-client \
          -no-webhook-server \
          {{.TASKFILE_DIR}}/openapi.bundle.yml
    deps:
      - install:ogen
    desc: Generates Go code with https://github.com/ogen-go/ogen
    sources:
      - >-
        {{.TASKFILE_DIR}}/openapi.bundle.yml
    generates:
      - >-
        {{.ROOT_DIR}}/pkg/http/v1/**
    preconditions:
      - test -s {{.TASKFILE_DIR}}/openapi.yml
      - test -s {{.ROOT_DIR}}/bin/ogen
    silent: true

  install:ogen:
    cmds:
      - >-
        GOBIN={{.ROOT_DIR}}/bin go install \
          github.com/ogen-go/ogen/cmd/ogen@v0.58.0
    status:
      - test -s {{.ROOT_DIR}}/bin/ogen
    silent: true
    internal: true
