/*
Change Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListIncidents200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIncidents200Response{}

// ListIncidents200Response struct for ListIncidents200Response
type ListIncidents200Response struct {
	Links Links `json:"_links"`
	Limit int32 `json:"limit"`
	Start int32 `json:"start"`
	Total int32 `json:"total"`
	Data []Incident `json:"data"`
}

// NewListIncidents200Response instantiates a new ListIncidents200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIncidents200Response(links Links, limit int32, start int32, total int32, data []Incident) *ListIncidents200Response {
	this := ListIncidents200Response{}
	this.Links = links
	this.Limit = limit
	this.Start = start
	this.Total = total
	this.Data = data
	return &this
}

// NewListIncidents200ResponseWithDefaults instantiates a new ListIncidents200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIncidents200ResponseWithDefaults() *ListIncidents200Response {
	this := ListIncidents200Response{}
	var limit int32 = 20
	this.Limit = limit
	var start int32 = 0
	this.Start = start
	return &this
}

// GetLinks returns the Links field value
func (o *ListIncidents200Response) GetLinks() Links {
	if o == nil {
		var ret Links
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ListIncidents200Response) GetLinksOk() (*Links, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ListIncidents200Response) SetLinks(v Links) {
	o.Links = v
}

// GetLimit returns the Limit field value
func (o *ListIncidents200Response) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *ListIncidents200Response) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *ListIncidents200Response) SetLimit(v int32) {
	o.Limit = v
}

// GetStart returns the Start field value
func (o *ListIncidents200Response) GetStart() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *ListIncidents200Response) GetStartOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *ListIncidents200Response) SetStart(v int32) {
	o.Start = v
}

// GetTotal returns the Total field value
func (o *ListIncidents200Response) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ListIncidents200Response) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ListIncidents200Response) SetTotal(v int32) {
	o.Total = v
}

// GetData returns the Data field value
func (o *ListIncidents200Response) GetData() []Incident {
	if o == nil {
		var ret []Incident
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListIncidents200Response) GetDataOk() ([]Incident, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListIncidents200Response) SetData(v []Incident) {
	o.Data = v
}

func (o ListIncidents200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIncidents200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_links"] = o.Links
	toSerialize["limit"] = o.Limit
	toSerialize["start"] = o.Start
	toSerialize["total"] = o.Total
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListIncidents200Response struct {
	value *ListIncidents200Response
	isSet bool
}

func (v NullableListIncidents200Response) Get() *ListIncidents200Response {
	return v.value
}

func (v *NullableListIncidents200Response) Set(val *ListIncidents200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListIncidents200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListIncidents200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIncidents200Response(val *ListIncidents200Response) *NullableListIncidents200Response {
	return &NullableListIncidents200Response{value: val, isSet: true}
}

func (v NullableListIncidents200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIncidents200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


