/*
Change Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListCRQ200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCRQ200ResponseAllOf{}

// ListCRQ200ResponseAllOf struct for ListCRQ200ResponseAllOf
type ListCRQ200ResponseAllOf struct {
	Data []Crq `json:"data"`
}

// NewListCRQ200ResponseAllOf instantiates a new ListCRQ200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCRQ200ResponseAllOf(data []Crq) *ListCRQ200ResponseAllOf {
	this := ListCRQ200ResponseAllOf{}
	this.Data = data
	return &this
}

// NewListCRQ200ResponseAllOfWithDefaults instantiates a new ListCRQ200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCRQ200ResponseAllOfWithDefaults() *ListCRQ200ResponseAllOf {
	this := ListCRQ200ResponseAllOf{}
	return &this
}

// GetData returns the Data field value
func (o *ListCRQ200ResponseAllOf) GetData() []Crq {
	if o == nil {
		var ret []Crq
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListCRQ200ResponseAllOf) GetDataOk() ([]Crq, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListCRQ200ResponseAllOf) SetData(v []Crq) {
	o.Data = v
}

func (o ListCRQ200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCRQ200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListCRQ200ResponseAllOf struct {
	value *ListCRQ200ResponseAllOf
	isSet bool
}

func (v NullableListCRQ200ResponseAllOf) Get() *ListCRQ200ResponseAllOf {
	return v.value
}

func (v *NullableListCRQ200ResponseAllOf) Set(val *ListCRQ200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableListCRQ200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableListCRQ200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCRQ200ResponseAllOf(val *ListCRQ200ResponseAllOf) *NullableListCRQ200ResponseAllOf {
	return &NullableListCRQ200ResponseAllOf{value: val, isSet: true}
}

func (v NullableListCRQ200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCRQ200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


