/*
Change Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListIncidents200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIncidents200ResponseAllOf{}

// ListIncidents200ResponseAllOf struct for ListIncidents200ResponseAllOf
type ListIncidents200ResponseAllOf struct {
	Data []Incident `json:"data"`
}

// NewListIncidents200ResponseAllOf instantiates a new ListIncidents200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIncidents200ResponseAllOf(data []Incident) *ListIncidents200ResponseAllOf {
	this := ListIncidents200ResponseAllOf{}
	this.Data = data
	return &this
}

// NewListIncidents200ResponseAllOfWithDefaults instantiates a new ListIncidents200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIncidents200ResponseAllOfWithDefaults() *ListIncidents200ResponseAllOf {
	this := ListIncidents200ResponseAllOf{}
	return &this
}

// GetData returns the Data field value
func (o *ListIncidents200ResponseAllOf) GetData() []Incident {
	if o == nil {
		var ret []Incident
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListIncidents200ResponseAllOf) GetDataOk() ([]Incident, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListIncidents200ResponseAllOf) SetData(v []Incident) {
	o.Data = v
}

func (o ListIncidents200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIncidents200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListIncidents200ResponseAllOf struct {
	value *ListIncidents200ResponseAllOf
	isSet bool
}

func (v NullableListIncidents200ResponseAllOf) Get() *ListIncidents200ResponseAllOf {
	return v.value
}

func (v *NullableListIncidents200ResponseAllOf) Set(val *ListIncidents200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableListIncidents200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableListIncidents200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIncidents200ResponseAllOf(val *ListIncidents200ResponseAllOf) *NullableListIncidents200ResponseAllOf {
	return &NullableListIncidents200ResponseAllOf{value: val, isSet: true}
}

func (v NullableListIncidents200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIncidents200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


