/*
Change Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateCRQRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCRQRequest{}

// CreateCRQRequest struct for CreateCRQRequest
type CreateCRQRequest struct {
	// The short-form description of change
	Summary string `json:"summary"`
	// The long-form description of change
	Description string `json:"description"`
	// The type of change
	Type *string `json:"type,omitempty"`
	// This flag indicates that change request should be closed  automatically
	IsAutoClose *bool `json:"isAutoClose,omitempty"`
}

// NewCreateCRQRequest instantiates a new CreateCRQRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCRQRequest(summary string, description string) *CreateCRQRequest {
	this := CreateCRQRequest{}
	this.Summary = summary
	this.Description = description
	var type_ string = "crq"
	this.Type = &type_
	var isAutoClose bool = false
	this.IsAutoClose = &isAutoClose
	return &this
}

// NewCreateCRQRequestWithDefaults instantiates a new CreateCRQRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCRQRequestWithDefaults() *CreateCRQRequest {
	this := CreateCRQRequest{}
	var type_ string = "crq"
	this.Type = &type_
	var isAutoClose bool = false
	this.IsAutoClose = &isAutoClose
	return &this
}

// GetSummary returns the Summary field value
func (o *CreateCRQRequest) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *CreateCRQRequest) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *CreateCRQRequest) SetSummary(v string) {
	o.Summary = v
}

// GetDescription returns the Description field value
func (o *CreateCRQRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateCRQRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateCRQRequest) SetDescription(v string) {
	o.Description = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateCRQRequest) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCRQRequest) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateCRQRequest) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateCRQRequest) SetType(v string) {
	o.Type = &v
}

// GetIsAutoClose returns the IsAutoClose field value if set, zero value otherwise.
func (o *CreateCRQRequest) GetIsAutoClose() bool {
	if o == nil || isNil(o.IsAutoClose) {
		var ret bool
		return ret
	}
	return *o.IsAutoClose
}

// GetIsAutoCloseOk returns a tuple with the IsAutoClose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCRQRequest) GetIsAutoCloseOk() (*bool, bool) {
	if o == nil || isNil(o.IsAutoClose) {
		return nil, false
	}
	return o.IsAutoClose, true
}

// HasIsAutoClose returns a boolean if a field has been set.
func (o *CreateCRQRequest) HasIsAutoClose() bool {
	if o != nil && !isNil(o.IsAutoClose) {
		return true
	}

	return false
}

// SetIsAutoClose gets a reference to the given bool and assigns it to the IsAutoClose field.
func (o *CreateCRQRequest) SetIsAutoClose(v bool) {
	o.IsAutoClose = &v
}

func (o CreateCRQRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCRQRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["summary"] = o.Summary
	toSerialize["description"] = o.Description
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.IsAutoClose) {
		toSerialize["isAutoClose"] = o.IsAutoClose
	}
	return toSerialize, nil
}

type NullableCreateCRQRequest struct {
	value *CreateCRQRequest
	isSet bool
}

func (v NullableCreateCRQRequest) Get() *CreateCRQRequest {
	return v.value
}

func (v *NullableCreateCRQRequest) Set(val *CreateCRQRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCRQRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCRQRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCRQRequest(val *CreateCRQRequest) *NullableCreateCRQRequest {
	return &NullableCreateCRQRequest{value: val, isSet: true}
}

func (v NullableCreateCRQRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCRQRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


