/*
Change Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateIncidentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIncidentRequest{}

// CreateIncidentRequest struct for CreateIncidentRequest
type CreateIncidentRequest struct {
	// The short-form description of change
	Summary string `json:"summary"`
	// The long-form description of change
	Description string `json:"description"`
}

// NewCreateIncidentRequest instantiates a new CreateIncidentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIncidentRequest(summary string, description string) *CreateIncidentRequest {
	this := CreateIncidentRequest{}
	this.Summary = summary
	this.Description = description
	return &this
}

// NewCreateIncidentRequestWithDefaults instantiates a new CreateIncidentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIncidentRequestWithDefaults() *CreateIncidentRequest {
	this := CreateIncidentRequest{}
	return &this
}

// GetSummary returns the Summary field value
func (o *CreateIncidentRequest) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *CreateIncidentRequest) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *CreateIncidentRequest) SetSummary(v string) {
	o.Summary = v
}

// GetDescription returns the Description field value
func (o *CreateIncidentRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateIncidentRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateIncidentRequest) SetDescription(v string) {
	o.Description = v
}

func (o CreateIncidentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIncidentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["summary"] = o.Summary
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

type NullableCreateIncidentRequest struct {
	value *CreateIncidentRequest
	isSet bool
}

func (v NullableCreateIncidentRequest) Get() *CreateIncidentRequest {
	return v.value
}

func (v *NullableCreateIncidentRequest) Set(val *CreateIncidentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIncidentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIncidentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIncidentRequest(val *CreateIncidentRequest) *NullableCreateIncidentRequest {
	return &NullableCreateIncidentRequest{value: val, isSet: true}
}

func (v NullableCreateIncidentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIncidentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


