/*
Change Management

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Crq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Crq{}

// Crq struct for Crq
type Crq struct {
	Links SelfLink `json:"_links"`
	// 
	Id string `json:"id"`
	// The short-form description of change
	Summary string `json:"summary"`
	// The long-form description of change
	Description string `json:"description"`
	// The type of change
	Type string `json:"type"`
	// This flag indicates that change request should be closed automatically
	IsAutoClose bool `json:"isAutoClose"`
	CreatedAt int64 `json:"createdAt"`
	UpdatedAt *int64 `json:"updatedAt,omitempty"`
}

// NewCrq instantiates a new Crq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrq(links SelfLink, id string, summary string, description string, type_ string, isAutoClose bool, createdAt int64) *Crq {
	this := Crq{}
	this.Links = links
	this.Id = id
	this.Summary = summary
	this.Description = description
	this.Type = type_
	this.IsAutoClose = isAutoClose
	this.CreatedAt = createdAt
	return &this
}

// NewCrqWithDefaults instantiates a new Crq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrqWithDefaults() *Crq {
	this := Crq{}
	var type_ string = "crq"
	this.Type = type_
	var isAutoClose bool = false
	this.IsAutoClose = isAutoClose
	return &this
}

// GetLinks returns the Links field value
func (o *Crq) GetLinks() SelfLink {
	if o == nil {
		var ret SelfLink
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *Crq) GetLinksOk() (*SelfLink, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *Crq) SetLinks(v SelfLink) {
	o.Links = v
}

// GetId returns the Id field value
func (o *Crq) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Crq) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Crq) SetId(v string) {
	o.Id = v
}

// GetSummary returns the Summary field value
func (o *Crq) GetSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *Crq) GetSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *Crq) SetSummary(v string) {
	o.Summary = v
}

// GetDescription returns the Description field value
func (o *Crq) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Crq) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Crq) SetDescription(v string) {
	o.Description = v
}

// GetType returns the Type field value
func (o *Crq) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Crq) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Crq) SetType(v string) {
	o.Type = v
}

// GetIsAutoClose returns the IsAutoClose field value
func (o *Crq) GetIsAutoClose() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAutoClose
}

// GetIsAutoCloseOk returns a tuple with the IsAutoClose field value
// and a boolean to check if the value has been set.
func (o *Crq) GetIsAutoCloseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAutoClose, true
}

// SetIsAutoClose sets field value
func (o *Crq) SetIsAutoClose(v bool) {
	o.IsAutoClose = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Crq) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Crq) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Crq) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Crq) GetUpdatedAt() int64 {
	if o == nil || isNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Crq) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || isNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Crq) HasUpdatedAt() bool {
	if o != nil && !isNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *Crq) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

func (o Crq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Crq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_links"] = o.Links
	toSerialize["id"] = o.Id
	toSerialize["summary"] = o.Summary
	toSerialize["description"] = o.Description
	toSerialize["type"] = o.Type
	toSerialize["isAutoClose"] = o.IsAutoClose
	toSerialize["createdAt"] = o.CreatedAt
	if !isNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableCrq struct {
	value *Crq
	isSet bool
}

func (v NullableCrq) Get() *Crq {
	return v.value
}

func (v *NullableCrq) Set(val *Crq) {
	v.value = val
	v.isSet = true
}

func (v NullableCrq) IsSet() bool {
	return v.isSet
}

func (v *NullableCrq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrq(val *Crq) *NullableCrq {
	return &NullableCrq{value: val, isSet: true}
}

func (v NullableCrq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


