// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateCRQRes interface {
	createCRQRes()
}

type CreateIncidentRes interface {
	createIncidentRes()
}

type GetCRQByIdRes interface {
	getCRQByIdRes()
}

type GetIncidentByIdRes interface {
	getIncidentByIdRes()
}

type ListCRQRes interface {
	listCRQRes()
}

type ListIncidentsRes interface {
	listIncidentsRes()
}
