@startuml Create AutoCRQ

participant "API Consumer" as consumer
participant "Change Management\nService" as cms
database Postgres as psql
participant "Issue Tracker" as tracker

consumer -> cms++: POST .../change-requests

cms -> cms: Validate request
alt Invalid request
cms --> consumer: HTTP 400 Bad Request
end

cms -> psql++: SELECT ...\nFROM change_requests\nWHERE external_id = $1
return Query result

alt Query error
cms --> consumer: HTTP 500 Internal Server Error
else Request exists
cms --> consumer: HTTP 200 OK {"id":"<id>"}
end

cms -> psql++: SELECT exists(...)
return Query result

alt Query error

end

return HTTP 201 Created {"id":"<id>"}

@enduml
