// Code generated by ogen, DO NOT EDIT.

package v1

// setDefaults set default value of fields.
func (s *CreateCRQReq) setDefaults() {
	{
		val := CreateCRQReqType("crq")
		s.Type.SetTo(val)
	}
	{
		val := bool(false)
		s.IsAutoClose.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Crq) setDefaults() {
	{
		val := CrqType("crq")
		s.Type = val
	}
	{
		val := bool(false)
		s.IsAutoClose = val
	}
}

// setDefaults set default value of fields.
func (s *Error) setDefaults() {
	{
		val := ErrorCode("internal")
		s.Code = val
	}
	{
		val := string("an internal error has occurred")
		s.Message = val
	}
}

// setDefaults set default value of fields.
func (s *ListCrq) setDefaults() {
	{
		val := LimitType(20)
		s.Limit = val
	}
	{
		val := StartType(0)
		s.Start = val
	}
}

// setDefaults set default value of fields.
func (s *ListIncidents) setDefaults() {
	{
		val := LimitType(20)
		s.Limit = val
	}
	{
		val := StartType(0)
		s.Start = val
	}
}
